import assert from 'node:assert/strict';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { ADVISORY_CONVERGENCE_CHECK_SELECTOR } from '../src/scripts/advisory-convergence.mts';
import {
  collectDocBudgetDriftViolations,
  collectDuplicateSyncPairTargets,
  collectGeneratedFromBannerViolations,
  collectInstructionSizeBudgetViolations,
  collectPolicyConfigDrift,
  generatedFromBanner,
  injectGeneratedFromBanner,
  inspectHelperRuntimeConfig,
  isBannerScopedInstructionTarget,
  normalizePolicyConfig,
  parseGeneratedFromBannerSource,
  resolveCollaboratorMarkerTrust,
  stripGeneratedFromBanner,
} from '../src/scripts/consistency-helpers.mts';
import { findPlaceholders } from '../src/scripts/idd-doctor.mts';
import { readJson, readText } from './test-utils.mts';

const SUITABILITY_PATH = new URL(
  '../.github/instructions/idd-suitability.instructions.md',
  import.meta.url,
);
const ROADMAP_AUDIT_PATH = new URL(
  '../.github/instructions/idd-roadmap-audit.instructions.md',
  import.meta.url,
);
const WORKFLOW_PATH = new URL('../docs/idd-workflow.md', import.meta.url);
const CUSTOMIZATION_PATH = new URL('../docs/customization.md', import.meta.url);

test('placeholder scenarios detect clean and dirty post-onboarding fixtures', () => {
  const clean = collectPlaceholderHits(
    new URL('./fixtures/consistency/placeholders/clean', import.meta.url),
  );
  const dirty = collectPlaceholderHits(
    new URL('./fixtures/consistency/placeholders/dirty', import.meta.url),
  );

  assert.deepEqual(clean, []);
  assert.deepEqual(dirty, [
    '.github/idd/config.json: {{PROJECT_MARKER_PREFIX}}, {{TRUSTED_MARKER_ACTOR}}',
    'README.md: {{REPO_NAME}}',
  ]);
});

test('instruction size budget skips with a notice when no git comparison base resolves', () => {
  let listed = false;
  const result = collectInstructionSizeBudgetViolations(
    { id: 'instruction-size-budgets', phaseLimitBytes: 1 },
    null,
    () => {
      listed = true;
      return ['idd-x.instructions.md'];
    },
    () => {
      throw new Error('must not read files on the null-base skip path');
    },
  );
  assert.equal(listed, false, 'must not list files on the null-base skip path');
  assert.deepEqual(result.errors, []);
  assert.deepEqual(result.notices, [
    'instruction-size-budgets: skipped instruction size budget check because no git comparison base was available',
  ]);
});

test('instruction size budget reads and audits only changed files, honoring both limits', () => {
  const texts: Record<string, string> = {
    'idd-phase.instructions.md': 'p'.repeat(120),
    'idd-core.instructions.md': `---\napplyTo: "**"\n---\n${'c'.repeat(120)}`,
    'idd-untouched.instructions.md': 'u'.repeat(10_000),
  };
  const readPaths: string[] = [];
  const result = collectInstructionSizeBudgetViolations(
    {
      id: 'instruction-size-budgets',
      alwaysLoadedLimitBytes: 50,
      phaseLimitBytes: 100,
    },
    new Set(['idd-phase.instructions.md', 'idd-core.instructions.md']),
    () => Object.keys(texts),
    (path) => {
      readPaths.push(path);
      return texts[path];
    },
  );
  // The unchanged file is never read (no wasted disk I/O on large repos).
  assert.deepEqual(readPaths.sort(), [
    'idd-core.instructions.md',
    'idd-phase.instructions.md',
  ]);
  assert.deepEqual(result.notices, []);
  assert.equal(result.errors.length, 2);
  assert.ok(
    result.errors.some((e) =>
      /idd-phase\.instructions\.md is 120 bytes .*phase/.test(e),
    ),
  );
  assert.ok(
    result.errors.some((e) =>
      /idd-core\.instructions\.md is \d+ bytes .*always-loaded/.test(e),
    ),
  );
});

test('instruction size budget returns nothing for absent config', () => {
  const result = collectInstructionSizeBudgetViolations(
    null,
    new Set(),
    () => {
      throw new Error('must not list files when config is absent');
    },
    () => {
      throw new Error('must not read files when config is absent');
    },
  );
  assert.deepEqual(result, { errors: [], notices: [] });
});

const BANNER_SOURCE =
  'idd-template/.github/instructions/idd-claim.instructions.md';

test('generated-from banner injects after frontmatter and round-trips', () => {
  const withFrontmatter = `---\napplyTo: "**"\nexcludeAgent: "code-review"\n---\n\n# Heading\n\nBody.\n`;
  const injected = injectGeneratedFromBanner(withFrontmatter, BANNER_SOURCE);
  // Banner sits after the closing frontmatter fence, before the heading.
  assert.match(
    injected,
    /---\n\n<!-- idd-generated-from:\n.+\nGenerated by sync-docs\..*\n.*-->\n\n# Heading/,
  );
  // Exact inverse restores the original byte-for-byte.
  assert.equal(stripGeneratedFromBanner(injected), withFrontmatter);
  assert.equal(parseGeneratedFromBannerSource(injected), BANNER_SOURCE);
});

test('generated-from banner injects at the top when there is no frontmatter and round-trips', () => {
  const noFrontmatter = '# Heading\n\nBody text.\n';
  const injected = injectGeneratedFromBanner(noFrontmatter, BANNER_SOURCE);
  assert.ok(injected.startsWith(`${generatedFromBanner(BANNER_SOURCE)}\n\n`));
  assert.ok(injected.endsWith(noFrontmatter));
  assert.equal(stripGeneratedFromBanner(injected), noFrontmatter);
  assert.equal(parseGeneratedFromBannerSource(injected), BANNER_SOURCE);
});

test('every generated-from banner line stays within the 80-char MD013 limit', () => {
  // Exercise the longest in-scope source path too — the banner's source line is
  // the only variable-length line, so a longer target would surface here.
  const longestSource =
    'idd-template/.github/instructions/idd-overview-appendix.instructions.md';
  for (const source of [BANNER_SOURCE, longestSource]) {
    for (const line of generatedFromBanner(source).split('\n')) {
      assert.ok(line.length <= 80, `banner line too long (${source}): ${line}`);
    }
  }
});

test('generated-from banner round-trips even without a blank line after frontmatter', () => {
  // A frontmatter block with no blank line before the heading is an edge shape
  // dprint/markdownlint would normally normalize, but strip must still be an
  // exact inverse of inject for it.
  const noBlank = '---\napplyTo: "**"\n---\n# Heading\n\nBody.\n';
  const injected = injectGeneratedFromBanner(noBlank, BANNER_SOURCE);
  assert.equal(stripGeneratedFromBanner(injected), noBlank);
  assert.equal(parseGeneratedFromBannerSource(injected), BANNER_SOURCE);
});

test('banner scope predicate covers only exact/concreted instruction targets', () => {
  assert.equal(
    isBannerScopedInstructionTarget(
      '.github/instructions/idd-claim.instructions.md',
      'exact',
    ),
    true,
  );
  assert.equal(
    isBannerScopedInstructionTarget(
      '.github/instructions/idd-work.instructions.md',
      'concreted',
    ),
    true,
  );
  // structure targets are validated structurally, not byte-generated.
  assert.equal(
    isBannerScopedInstructionTarget(
      '.github/instructions/idd-discover.instructions.md',
      'structure',
    ),
    false,
  );
  // generated docs / skills targets are a deliberate follow-up, out of scope.
  assert.equal(
    isBannerScopedInstructionTarget('docs/concepts.md', 'exact'),
    false,
  );
});

test('parseGeneratedFromBannerSource returns null without a banner', () => {
  assert.equal(parseGeneratedFromBannerSource('# Heading\n\nBody.\n'), null);
});

test('parseGeneratedFromBannerSource ignores a banner-shaped comment out of position', () => {
  // A banner is only recognized at the top or immediately after frontmatter; a
  // copy pasted mid-body must not be accepted as the generated-from banner.
  const midBody = `# Heading\n\nSome text.\n\n${generatedFromBanner(
    BANNER_SOURCE,
  )}\n\nMore text.\n`;
  assert.equal(parseGeneratedFromBannerSource(midBody), null);
});

test('collectGeneratedFromBannerViolations passes when the banner matches, fails on missing/wrong', () => {
  const target = '.github/instructions/idd-claim.instructions.md';
  const pairs = [
    { id: 'idd-claim', source: BANNER_SOURCE, target, mode: 'exact' },
    // A structure target must be ignored even if it has no banner.
    {
      id: 'idd-discover',
      source: 'idd-template/.github/instructions/idd-discover.instructions.md',
      target: '.github/instructions/idd-discover.instructions.md',
      mode: 'structure',
    },
  ];
  const good = injectGeneratedFromBanner('# Heading\n\nBody.\n', BANNER_SOURCE);

  // Passing case: correct banner, structure target skipped.
  assert.deepEqual(
    collectGeneratedFromBannerViolations(pairs, (path) =>
      path === target ? good : '# discover\n',
    ),
    [],
  );

  // Missing-marker case: the target carries no banner.
  const missing = collectGeneratedFromBannerViolations(pairs, (path) =>
    path === target ? '# Heading\n\nBody.\n' : '# discover\n',
  );
  assert.equal(missing.length, 1);
  assert.match(
    missing[0],
    /idd-claim:.*missing a well-formed idd-generated-from banner/,
  );

  // Wrong-source case: banner names a different source.
  const wrong = collectGeneratedFromBannerViolations(pairs, (path) =>
    path === target
      ? injectGeneratedFromBanner(
          '# Heading\n\nBody.\n',
          'idd-template/.github/instructions/idd-merge.instructions.md',
        )
      : '# discover\n',
  );
  assert.equal(wrong.length, 1);
  assert.match(
    wrong[0],
    /banner names .*idd-merge.*but its source is .*idd-claim/,
  );
});

test('collectGeneratedFromBannerViolations is not fooled by a canonical banner copy-pasted elsewhere', () => {
  const target = '.github/instructions/idd-claim.instructions.md';
  const pairs = [
    { id: 'idd-claim', source: BANNER_SOURCE, target, mode: 'exact' },
  ];
  // The in-position banner is malformed (tampered note line), but a correct
  // canonical banner is copy-pasted lower in the file. The check must still fail
  // on the in-position banner rather than matching the pasted copy.
  const tamperedInPosition = [
    '<!-- idd-generated-from:',
    BANNER_SOURCE,
    'TAMPERED note line that is not the canonical text',
    '`node scripts/sync-docs.mjs --apply`; do not edit this file. -->',
  ].join('\n');
  const text = `${tamperedInPosition}\n\n# Heading\n\nExample:\n\n${generatedFromBanner(
    BANNER_SOURCE,
  )}\n\nBody.\n`;
  const result = collectGeneratedFromBannerViolations(pairs, () => text);
  assert.equal(result.length, 1);
  assert.match(result[0], /idd-claim:.*generated-from banner is malformed/);
});

test('instruction size budget excludes the generated-from banner from the measured size', () => {
  const target = 'idd-claim.instructions.md';
  const source = BANNER_SOURCE;
  const contentUnderBudget = `# Heading\n\n${'x'.repeat(60)}\n`;
  const withBanner = injectGeneratedFromBanner(contentUnderBudget, source);
  // The banner inflates the raw bytes over the limit, but the measured size
  // (banner stripped) is the content size, which is under budget.
  assert.ok(Buffer.byteLength(withBanner, 'utf8') > 100);
  const result = collectInstructionSizeBudgetViolations(
    {
      id: 'instruction-size-budgets',
      alwaysLoadedLimitBytes: 50,
      phaseLimitBytes: 100,
    },
    new Set([target]),
    () => [target],
    () => withBanner,
  );
  assert.deepEqual(result.errors, []);
});

const DOC_BUDGET_SIZE = {
  alwaysLoadedLimitBytes: 20_000,
  phaseLimitBytes: 35_500,
};
// Keep representative of live audit/sync-manifest.json bundleBudgets
// (standard + lite independent ceilings currently on main).
const DOC_BUDGET_BUNDLES = [
  { limitBytes: 112_700 },
  { limitBytes: 45_000 },
  { limitBytes: 24_000 },
  { limitBytes: 16_000 },
];

test('doc budget guard passes when documented values match the manifest', () => {
  const texts: Record<string, string> = {
    'README.md': '| Phase | 35,500 bytes |\n| Always | 20,000 bytes |',
    // a hardcoded bundle value that still matches the manifest is allowed
    'strategy.md': 'discovery bundle is 112,700 bytes',
    // a doc that reads limits live via jq carries no number → never flagged
    'jq.md':
      "read the live values with jq '.bundleBudgets' audit/sync-manifest.json",
  };
  const result = collectDocBudgetDriftViolations(
    { files: ['README.md', 'strategy.md', 'jq.md'] },
    DOC_BUDGET_SIZE,
    DOC_BUDGET_BUNDLES,
    (path) => texts[path],
  );
  assert.deepEqual(result, { errors: [], notices: [] });
});

test('doc budget guard flags a value that drifted from every manifest budget', () => {
  const result = collectDocBudgetDriftViolations(
    { id: 'doc-budget-drift', files: ['README.md'] },
    DOC_BUDGET_SIZE,
    DOC_BUDGET_BUNDLES,
    () => '| Phase instruction file | 30,000 bytes |',
  );
  assert.equal(result.errors.length, 1);
  assert.match(
    result.errors[0],
    /doc-budget-drift: README\.md states 30,000 bytes, which is not a current sync-manifest budget value \(valid: 16000, 20000, 24000, 35500, 45000, 112700\)/,
  );
});

test('doc budget guard is a no-op without config and notices on empty budgets', () => {
  assert.deepEqual(
    collectDocBudgetDriftViolations(
      null,
      DOC_BUDGET_SIZE,
      DOC_BUDGET_BUNDLES,
      () => {
        throw new Error('must not read files when config is absent');
      },
    ),
    { errors: [], notices: [] },
  );
  const noBudgets = collectDocBudgetDriftViolations(
    { id: 'doc-budget-drift', files: ['README.md'] },
    null,
    [],
    () => '32,200 bytes',
  );
  assert.deepEqual(noBudgets.errors, []);
  assert.equal(noBudgets.notices.length, 1);
  assert.match(noBudgets.notices[0], /skipped doc budget guard/);
});

test('config drift scenarios detect mismatches between config and overview defaults', () => {
  const overview = readText('tests/fixtures/consistency/config/overview.txt');
  const missingRowOverview = readText(
    'tests/fixtures/consistency/config/overview-missing-policy-row.txt',
  );
  const aligned = readJson(
    'tests/fixtures/consistency/config/aligned-config.json',
  );
  const drifted = readJson(
    'tests/fixtures/consistency/config/drifted-config.json',
  );

  assert.deepEqual(collectPolicyConfigDrift(aligned, overview), []);
  assert.deepEqual(collectPolicyConfigDrift(drifted, overview), [
    {
      path: 'commands.fix-validate',
      expected: 'npm run fix',
      actual: 'npm run fix && npm test',
    },
    {
      path: 'issueScope',
      expected: 'roadmap',
      actual: 'orphan-first',
    },
  ]);
  assert.deepEqual(collectPolicyConfigDrift(aligned, missingRowOverview), [
    {
      path: 'orphanFirstPolicy',
      expected: null,
      actual: null,
      reason: 'missing instruction row orphan-first-policy',
    },
  ]);
});

test('helper runtime inspection accepts absent and supported profiles, rejects unsupported values', () => {
  assert.deepEqual(inspectHelperRuntimeConfig({}), {
    status: 'absent',
  });
  assert.deepEqual(inspectHelperRuntimeConfig('invalid'), {
    status: 'invalid',
    reason: 'config must be a non-null object',
  });
  assert.deepEqual(inspectHelperRuntimeConfig([]), {
    status: 'invalid',
    reason: 'config must be a non-null object',
  });
  assert.deepEqual(
    inspectHelperRuntimeConfig({
      helperRuntime: {
        profile: 'instructions-only',
      },
    }),
    {
      status: 'ok',
      profile: 'instructions-only',
    },
  );
  for (const profile of ['package-manager', 'vendored-node', 'ephemeral-npx']) {
    assert.deepEqual(
      inspectHelperRuntimeConfig({
        helperRuntime: {
          profile,
        },
      }),
      {
        status: 'ok',
        profile,
      },
    );
  }
  assert.deepEqual(
    inspectHelperRuntimeConfig({
      helperRuntime: {
        profile: 'bun',
      },
    }),
    {
      status: 'invalid',
      reason: 'unsupported helperRuntime.profile "bun"',
    },
  );
  assert.deepEqual(
    inspectHelperRuntimeConfig({
      helperRuntime: {
        profile: 'package-manager',
        manager: 'pnpm',
      },
    }),
    {
      status: 'invalid',
      reason: 'unsupported helperRuntime keys: manager',
    },
  );
});

test('policy normalization provides default-safe values and supports aliases', () => {
  assert.deepEqual(normalizePolicyConfig(null), {
    issueScope: 'roadmap-first',
    orphanFirstPolicy: 'none',
    skipIssueAuthorApprovalGate: false,
    maintainerApprovalActorPolicy: 'owners-and-maintainers-only',
    stallRecovery: {
      quietWindow: 'PT30M',
    },
    claimTiming: {
      staleAge: 'PT24H',
    },
    forcedHandoff: {
      mode: 'disabled',
      authorityPolicy: 'owners-and-maintainers-only',
    },
    markerTrust: {
      allowCollaboratorMarkers: false,
    },
    advisoryWait: {
      requestCap: 30,
      pendingWindow: 'PT30M',
      settledWindow: 'PT10M',
      pollInterval: 'PT2M',
      capExhaustedRoute: 'phase-specific',
    },
    ciWait: {
      runningTimeout: 'PT30M',
      generationTimeout: 'PT10M',
      rerunPolicy: 'rerun-once',
    },
    ciGate: {
      externalChecks: {
        advisory: [],
        waivable: [],
      },
      externalCheckWaivers: {
        mode: 'disabled',
        authorityPolicy: 'owners-and-maintainers-only',
        maxValidity: 'PT24H',
      },
      trustEmptyProtectionReads: false,
    },
    discover: {
      activeClaimPreScanBatchSize: 10,
      selectionDesync: 'off',
      legacyRoots: [],
    },
    claim: {
      verifySettleDelay: 'PT5S',
    },
    critiqueLoop: {
      cPhaseLowSeveritySkipAfter: 3,
      e10NoProgressHoldAfter: 3,
    },
    reviewEscalation: {
      changesRequestedFirstEscalation: 'PT24H',
      changesRequestedSecondEscalation: 'PT48H',
    },
    approvalSignals: {
      readyLabelName: 'idd:ready',
      labelFreshnessMode: 'presence-only',
    },
    issueAuthoring: {
      maxClarificationRounds: 3,
      authoringLabelName: 'status:authoring',
      authoringStaleAge: 'PT4H',
    },
    labels: {
      roadmapLabelName: 'roadmap',
      blockedByHumanLabelName: 'status:blocked-by-human',
      needsDecisionLabelName: 'status:needs-decision',
    },
    mergeGate: {
      soloCodeownerAdminFallback: 'auto-admin-retry',
    },
  });

  const defaultPolicy = normalizePolicyConfig(null);
  for (const key of [
    'claimRevalidationGate',
    'untrustedMarkerAuthority',
    'forcedHandoffInitiator',
    'approvalNeededFallbackAutoClaim',
  ]) {
    assert.equal(
      Object.hasOwn(defaultPolicy, key),
      false,
      `${key} must stay non-configurable`,
    );
  }

  assert.deepEqual(
    normalizePolicyConfig({
      issueScope: 'orphan-first',
      orphanFirstPolicy: 'maintainer-approved',
      skipIssueAuthorApprovalGate: true,
      maintainerApprovalActorPolicy: 'all-write-permission-actors',
      stallRecovery: {
        quietWindow: 'PT45M',
      },
      claimTiming: {
        staleAge: 'PT18H',
      },
      forcedHandoffMode: 'human-gated',
      'forced-handoff-authority': 'all-write-permission-actors',
      markerTrustAllowCollaboratorMarkers: true,
      advisoryWait: {
        requestCap: 5,
        pendingWindow: 'PT40M',
        settledWindow: 'PT11M',
        pollInterval: 'PT3M',
        capExhaustedRoute: 'hold',
      },
      ciWait: {
        runningTimeout: 'PT35M',
        generationTimeout: 'PT15M',
        rerunPolicy: 'rerun-once',
      },
      ciGate: {
        externalChecks: {
          advisory: [{ selector: 'Copilot code review', matchMode: 'exact' }],
          waivable: [{ selector: 'CodeRabbit*', matchMode: 'glob' }],
        },
        externalCheckWaivers: {
          mode: 'maintainer-authorized',
          authorityPolicy: 'all-write-permission-actors',
          maxValidity: 'PT12H',
        },
        trustEmptyProtectionReads: true,
      },
      discover: {
        activeClaimPreScanBatchSize: 11,
        selectionDesync: 'session-offset',
        legacyRoots: [42, 7],
      },
      claim: {
        verifySettleDelay: 'PT7S',
      },
      critiqueLoop: {
        cPhaseLowSeveritySkipAfter: 4,
        e10NoProgressHoldAfter: 2,
      },
      reviewEscalation: {
        changesRequestedFirstEscalation: 'PT18H',
        changesRequestedSecondEscalation: 'PT36H',
      },
      approvalSignals: {
        readyLabelName: 'custom:ready',
        labelFreshnessMode: 'event-freshness',
      },
      issueAuthoring: {
        maxClarificationRounds: 4,
        authoringLabelName: 'status:drafting',
        authoringStaleAge: 'PT3H',
      },
      labels: {
        roadmapLabelName: 'epic',
        blockedByHumanLabelName: 'blocked:human',
        needsDecisionLabelName: 'needs:decision',
      },
      mergeGate: {
        soloCodeownerAdminFallback: 'hold-and-report',
      },
    }),
    {
      issueScope: 'orphan-first',
      orphanFirstPolicy: 'maintainer-approved',
      skipIssueAuthorApprovalGate: true,
      maintainerApprovalActorPolicy: 'all-write-permission-actors',
      stallRecovery: {
        quietWindow: 'PT45M',
      },
      claimTiming: {
        staleAge: 'PT18H',
      },
      forcedHandoff: {
        mode: 'human-gated',
        authorityPolicy: 'all-write-permission-actors',
      },
      markerTrust: {
        allowCollaboratorMarkers: true,
      },
      advisoryWait: {
        requestCap: 5,
        pendingWindow: 'PT40M',
        settledWindow: 'PT11M',
        pollInterval: 'PT3M',
        capExhaustedRoute: 'hold',
      },
      ciWait: {
        runningTimeout: 'PT35M',
        generationTimeout: 'PT15M',
        rerunPolicy: 'rerun-once',
      },
      ciGate: {
        externalChecks: {
          advisory: [{ selector: 'Copilot code review', matchMode: 'exact' }],
          waivable: [{ selector: 'CodeRabbit*', matchMode: 'glob' }],
        },
        externalCheckWaivers: {
          mode: 'maintainer-authorized',
          authorityPolicy: 'all-write-permission-actors',
          maxValidity: 'PT12H',
        },
        trustEmptyProtectionReads: true,
      },
      discover: {
        activeClaimPreScanBatchSize: 11,
        selectionDesync: 'session-offset',
        legacyRoots: [42, 7],
      },
      claim: {
        verifySettleDelay: 'PT7S',
      },
      critiqueLoop: {
        cPhaseLowSeveritySkipAfter: 4,
        e10NoProgressHoldAfter: 2,
      },
      reviewEscalation: {
        changesRequestedFirstEscalation: 'PT18H',
        changesRequestedSecondEscalation: 'PT36H',
      },
      approvalSignals: {
        readyLabelName: 'custom:ready',
        labelFreshnessMode: 'event-freshness',
      },
      issueAuthoring: {
        maxClarificationRounds: 4,
        authoringLabelName: 'status:drafting',
        authoringStaleAge: 'PT3H',
      },
      labels: {
        roadmapLabelName: 'epic',
        blockedByHumanLabelName: 'blocked:human',
        needsDecisionLabelName: 'needs:decision',
      },
      mergeGate: {
        soloCodeownerAdminFallback: 'hold-and-report',
      },
    },
  );

  assert.deepEqual(
    normalizePolicyConfig({
      forcedHandoff: {
        mode: 'human-gated',
        authorityPolicy: 'owners-and-maintainers-only',
      },
      'forced-handoff-authority': 'all-write-permission-actors',
    }).forcedHandoff,
    {
      mode: 'human-gated',
      authorityPolicy: 'owners-and-maintainers-only',
    },
  );

  assert.deepEqual(
    normalizePolicyConfig({
      forcedHandoff: {
        mode: 'human-gated-invalid',
        authorityPolicy: 'owners-and-maintainers-invalid',
      },
      forcedHandoffMode: 'human-gated',
      'forced-handoff-authority': 'all-write-permission-actors',
    }).forcedHandoff,
    {
      mode: 'human-gated',
      authorityPolicy: 'all-write-permission-actors',
    },
  );

  assert.deepEqual(
    normalizePolicyConfig({
      advisoryWait: {
        pendingWindow: 'PT60S',
        settledWindow: 'PT0M',
        pollInterval: 'PT90S',
        capExhaustedRoute: 'phase-default',
      },
    }).advisoryWait,
    {
      requestCap: 30,
      pendingWindow: 'PT30M',
      settledWindow: 'PT10M',
      pollInterval: 'PT2M',
      capExhaustedRoute: 'phase-specific',
    },
  );

  assert.deepEqual(
    normalizePolicyConfig({
      advisoryWait: {
        capExhaustedRoute: 'strict-hold',
      },
    }).advisoryWait.capExhaustedRoute,
    'hold',
  );

  assert.deepEqual(
    normalizePolicyConfig({
      ciGate: {
        externalChecks: {
          advisory: [{ selector: '', matchMode: 'regex' }],
        },
        externalCheckWaivers: {
          mode: 'always-on',
          authorityPolicy: 'owners-only',
          maxValidity: 'PT',
        },
      },
    }).ciGate,
    {
      externalChecks: {
        advisory: [],
        waivable: [],
      },
      externalCheckWaivers: {
        mode: 'disabled',
        authorityPolicy: 'owners-and-maintainers-only',
        maxValidity: 'PT24H',
      },
      trustEmptyProtectionReads: false,
    },
  );

  assert.deepEqual(
    normalizePolicyConfig({
      ciGate: {
        externalChecks: {
          waivable: [
            { selector: 'CodeRabbit*', matchMode: 'glob', extra: true },
          ],
        },
      },
    }).ciGate.externalChecks,
    {
      advisory: [],
      waivable: [],
    },
  );

  // #1377: a non-boolean value fails closed to `false` (the safe default),
  // matching every other `=== true` boolean field in this normalizer.
  assert.equal(
    normalizePolicyConfig({
      ciGate: { trustEmptyProtectionReads: 'true' },
    }).ciGate.trustEmptyProtectionReads,
    false,
  );
  assert.equal(
    normalizePolicyConfig({
      ciGate: { trustEmptyProtectionReads: true },
    }).ciGate.trustEmptyProtectionReads,
    true,
  );
});

test('collaborator trust resolution honors aliases and env fallback', () => {
  assert.equal(resolveCollaboratorMarkerTrust({}, 'true'), true);
  assert.equal(
    resolveCollaboratorMarkerTrust(
      {
        markerTrustAllowCollaboratorMarkers: true,
      },
      '',
    ),
    true,
  );
  assert.equal(
    resolveCollaboratorMarkerTrust(
      {
        allowCollaboratorMarkers: false,
      },
      'true',
    ),
    false,
  );
  assert.equal(
    resolveCollaboratorMarkerTrust(
      {
        markerTrust: {
          allowCollaboratorMarkers: 'invalid',
        },
      },
      'true',
    ),
    true,
  );
});

test('A4.5 outcome fixtures match the documented check-to-outcome mapping', () => {
  const text = readFileSync(SUITABILITY_PATH, 'utf8');
  const checks = extractCheckOutcomes(text);
  const outcomes = extractOutcomeTable(text);
  const cases = readJson('tests/fixtures/consistency/a45-outcomes.json') as {
    id: string;
    failedCheck: string;
    expectedOutcome: string;
  }[];

  for (const fixture of cases) {
    assert.equal(
      checks.get(fixture.failedCheck),
      fixture.expectedOutcome,
      fixture.id,
    );
    assert.ok(outcomes.has(fixture.expectedOutcome), fixture.expectedOutcome);
  }

  assert.deepEqual(
    [...new Set(cases.map((fixture) => fixture.expectedOutcome))].sort(),
    [
      'blocked-by-human',
      'duplicate',
      'invalid',
      'needs-decision',
      'out-of-scope',
      'unclear',
    ],
  );
  assert.match(outcomes.get('invalid') ?? '', /do not retry/i);
});

test('discover A2 roadmap node classification guidance is present in instruction and docs surfaces', () => {
  const discover = readFileSync(
    new URL(
      '../.github/instructions/idd-discover.instructions.md',
      import.meta.url,
    ),
    'utf8',
  );
  const templateDiscover = readFileSync(
    new URL(
      '../idd-template/.github/instructions/idd-discover.instructions.md',
      import.meta.url,
    ),
    'utf8',
  );
  const workflow = readFileSync(WORKFLOW_PATH, 'utf8');
  const templateWorkflow = readFileSync(
    new URL('../idd-template/docs/idd-workflow.md', import.meta.url),
    'utf8',
  );

  assert.match(discover, /roadmap node/i);
  assert.match(discover, /execution leaf/i);
  assert.match(discover, /only open roadmap nodes remain/i);
  assert.match(discover, /A3\/A4\/A4\.5\/A5/i);
  assert.match(workflow, /classify roadmap/i);

  assert.match(templateDiscover, /roadmap node/i);
  assert.match(templateDiscover, /execution leaf/i);
  assert.match(templateDiscover, /only open roadmap nodes remain/i);
  assert.match(templateDiscover, /A3\/A4\/A4\.5\/A5/i);
  assert.match(templateWorkflow, /classify roadmap/i);
});

test('recursive roadmap audit guidance stays aligned across instruction and docs surfaces', () => {
  const audit = readFileSync(ROADMAP_AUDIT_PATH, 'utf8');
  const workflow = readFileSync(WORKFLOW_PATH, 'utf8');
  const customization = readFileSync(CUSTOMIZATION_PATH, 'utf8');

  assert.match(audit, /nested roadmaps?/i);
  assert.match(audit, /bottom-up/i);
  assert.match(audit, /exact roadmap issue being mutated/i);
  assert.match(workflow, /nested roadmap/i);
  assert.match(workflow, /bottom-up/i);
  assert.match(customization, /bottom-up/i);
  assert.match(customization, /exact roadmap node being mutated/i);
});

function collectPlaceholderHits(url: URL): string[] {
  const root = fileURLToPath(url);
  const hits: string[] = [];

  walk(root, (fullPath) => {
    const placeholders = [
      ...new Set(findPlaceholders(readFileSync(fullPath, 'utf8'))),
    ];
    if (placeholders.length === 0) {
      return;
    }
    const relativePath = relative(root, fullPath).replaceAll('\\', '/');
    hits.push(`${relativePath}: ${placeholders.join(', ')}`);
  });

  return hits.sort();
}

function walk(directory: string, visit: (fullPath: string) => void): void {
  for (const entry of readdirSync(directory)) {
    const fullPath = join(directory, entry);
    const stats = statSync(fullPath);
    if (stats.isDirectory()) {
      walk(fullPath, visit);
      continue;
    }
    visit(fullPath);
  }
}

function extractCheckOutcomes(text: string): Map<string, string> {
  const entries = [
    ...text.matchAll(
      /^### Check \d+: ([^\n]+)\n[\s\S]*?^- \*\*Outcome on fail\*\*: `([^`]+)`$/gm,
    ),
  ];
  return new Map(
    entries.map(
      ([, heading, outcome]) => [heading.trim(), outcome] as [string, string],
    ),
  );
}

function extractOutcomeTable(text: string): Map<string, string> {
  const sectionMatch = text.match(
    /## Failure Outcomes[\s\S]*?\n\| Outcome[\s\S]*?\n((?:\|[^\n]+\n)+)/,
  );
  const rows = (sectionMatch?.[1] ?? '')
    .split(/\r?\n/)
    .filter((row) => row.startsWith('| `'));
  return new Map(
    rows.map((row) => {
      const cells = row
        .split('|')
        .slice(1, -1)
        .map((cell) => cell.trim());
      return [cells[0].replaceAll('`', ''), cells[2]] as [string, string];
    }),
  );
}

test('package.json version stays aligned with iddVersion in the shipped and template configs', () => {
  const packageJson = JSON.parse(
    readFileSync(new URL('../package.json', import.meta.url), 'utf8'),
  );
  for (const configPath of [
    '.github/idd/config.json',
    'idd-template/.github/idd/config.json',
  ]) {
    const config = JSON.parse(
      readFileSync(new URL(`../${configPath}`, import.meta.url), 'utf8'),
    );
    assert.equal(
      packageJson.version,
      config.iddVersion,
      `package.json version (${packageJson.version}) must equal iddVersion ` +
        `(${config.iddVersion}) in ${configPath}`,
    );
  }
});

test('#1512: this repository opts into the advisory-convergence maintainer-waiver backstop, while the distributed template config stays disabled', () => {
  const repoPolicy = normalizePolicyConfig(readJson('.github/idd/config.json'));
  assert.equal(
    repoPolicy.ciGate.externalCheckWaivers.mode,
    'maintainer-authorized',
  );
  assert.ok(
    repoPolicy.ciGate.externalChecks.waivable.some(
      (entry) =>
        entry.selector === ADVISORY_CONVERGENCE_CHECK_SELECTOR &&
        entry.matchMode === 'exact',
    ),
    `expected ${ADVISORY_CONVERGENCE_CHECK_SELECTOR} to be registered under ` +
      'ciGate.externalChecks.waivable with matchMode "exact" (not a ' +
      'broader glob) in .github/idd/config.json',
  );

  const templatePolicy = normalizePolicyConfig(
    readJson('idd-template/.github/idd/config.json'),
  );
  assert.equal(templatePolicy.ciGate.externalCheckWaivers.mode, 'disabled');
  assert.deepEqual(templatePolicy.ciGate.externalChecks.waivable, []);
});

test('collectDuplicateSyncPairTargets flags repeated targets and ignores unique ones', () => {
  assert.deepEqual(
    collectDuplicateSyncPairTargets([
      { id: 'a', target: 'x.md' },
      { id: 'b', target: 'y.md' },
    ]),
    [],
  );
  // Non-array / empty / missing / non-string targets are not violations:
  // invalid entries are ignored rather than coerced into a fake duplicate.
  assert.deepEqual(collectDuplicateSyncPairTargets(undefined), []);
  assert.deepEqual(collectDuplicateSyncPairTargets([{ id: 'a' }]), []);
  assert.deepEqual(
    collectDuplicateSyncPairTargets([
      { id: 'a', target: {} },
      { id: 'b', target: {} },
    ]),
    [],
  );

  const dupes = collectDuplicateSyncPairTargets([
    { id: 'first', target: 'shared.md' },
    { id: 'other', target: 'unique.md' },
    { id: 'second', target: 'shared.md' },
  ]);
  assert.equal(dupes.length, 1);
  assert.match(dupes[0], /duplicate target "shared\.md"/);
  assert.match(dupes[0], /pair "second"/);
});

test('audit/sync-manifest.json has no duplicate syncPairs targets', () => {
  const manifest = JSON.parse(
    readFileSync(
      new URL('../audit/sync-manifest.json', import.meta.url),
      'utf8',
    ),
  ) as { syncPairs?: { id?: string; target?: string }[] };
  assert.deepEqual(collectDuplicateSyncPairTargets(manifest.syncPairs), []);
});

test('audit/sync-manifest.json guards the .claude issue-authoring markdown mirror with a fileSet', () => {
  const manifest = JSON.parse(
    readFileSync(
      new URL('../audit/sync-manifest.json', import.meta.url),
      'utf8',
    ),
  ) as {
    fileSets?: {
      id?: string;
      sourceGlob?: string;
      targetGlob?: string;
      match?: string;
      requireSyncPairs?: boolean;
    }[];
  };
  const fileSet = manifest.fileSets?.find(
    (entry) => entry.id === 'claude-skills-issue-authoring-markdown-set',
  );
  assert.deepEqual(fileSet, {
    id: 'claude-skills-issue-authoring-markdown-set',
    sourceGlob: 'skills/issue-authoring/**/*.md',
    targetGlob: '.claude/skills/issue-authoring/**/*.md',
    match: 'basename',
    requireSyncPairs: true,
  });
});
